### ISSUE TITLE
Unknown client identifier: deuwo_mia_app

### ISSUE THREAD

**Issue by thepiwo** [inverse/python-iolite-client#217]
Hello,

I stumbled across your project as I am trying to programatically control my IOLITE "smart home", where the app doesn't seem to be available any more.

Unfortunately after decoding the QR code any trying to do the oauth client initialization via your library I receive status 500 with the error "Unknown client identifier: deuwo_mia_app including an internal stack trace from remote.iolite.de.

Do you know if there are any other client ids that might work or do you also experience the api not be available any more?

Kind regards

**Comment by inverse** [comment]
Yeah it looks like they revoked the MIA app from the play store. Not sure why they did that.

I'm not that versed with the full offering that IOLITE provide. Was it something that was installed for you? Was there another app provided for your setup?

**Comment by thepiwo** [comment]
Yes, my device looks different than the Deutsche Wohnen variant.

![image](https://github.com/inverse/python-iolite-client/assets/6539235/499b721e-8ead-4a79-acae-97dde8f31660)
![image](https://github.com/inverse/python-iolite-client/assets/6539235/2541f19a-83e6-4143-a327-92dc77d818f9)

but your question prompted me to try and find the correct app, found a copy of "Digitaler Wohnungsassistent_0.6", decompiled using jadx, managed to find the client id `iq_diwa_app` and with this the login seems to work.

I will be trying to figure out the rest of the python code myself, the control for my heating (in-floor) and blinds seems to work a bit different than the current code assumes (e.g. no batteryLevel prop).

When I hacked something together I'll provide a PR eventually.
